CREATE TABLE attachment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  path TEXT NOT NULL,
  task INTEGER UNSIGNED NOT NULL
);

CREATE TABLE category (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  colour INTEGER UNSIGNED NOT NULL
);

CREATE TABLE note (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  task INTEGER UNSIGNED NOT NULL
);

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT NULL,
  colour INTEGER UNSIGNED NOT NULL,
  priority INTEGER UNSIGNED NOT NULL,
  creation_date TEXT NOT NULL,
  due_date TEXT NULL,
  completed TEXT NULL,
  timer TEXT NULL,
  price TEXT NULL,
  paid TEXT NULL,
  payment TEXT NULL,
  payment_note TEXT NULL,
  parent INTEGER UNSIGNED NULL,
  category INTEGER UNSIGNED NOT NULL
);

